const menu = [
  {
    id: 1,
    title: "Poundo Yam",
    category: "breakfast",
    price: 5000,
    img: "./images/item-1.jpeg",
    desc: `Our poundo yam is best served with confirm cold trophy under good air conditioning FileSystem. Just try it today`,
  },
  {
    id: 2,
    title: "Chicken and Chips",
    category: "lunch",
    price: 9500,
    img: "./images/item-2.jpeg",
    desc: `Chicken and chips is very good for the body. Our chickens are imported from brazil and they have good nutritional values. When you...`,
  },
  {
    id: 3,
    title: "Isi Ewu",
    category: "shakes",
    price: 6990,
    img: "./images/item-3.jpeg",
    desc: `Isi Ewu is a dish that is usually mistaken for the dish Nkwobi because they both have similar ingredients. However, just as the name rings...`,
  },
  {
    id: 4,
    title: "Curry Spaghetti",
    category: "breakfast",
    price: 2000,
    img: "./images/item-4.jpeg",
    desc: `Take your spaghetti game to the next level with these fun, classic, easy recipes for topping `,
  },
  {
    id: 5,
    title: "Amala and Isi-ewu",
    category: "lunch",
    price: 3900,
    img: "./images/item-5.jpeg",
    desc: ` If you are not familiar with this delicacy, let me give you a brief introduction. Amala is made from yam flour (Elubo) and is a Nigerian Cuisine . `,
  },
  {
    id: 6,
    title: "Eba with Afang",
    category: "shakes",
    price: 1899,
    img: "./images/item-6.jpeg",
    desc: `Swallows are a category of soft cooked dough that can be made from roots, tubers, vegetables, and more, served as a starch at mealtimes.`,
  },
  {
    id: 7,
    title: "Bread and Ewa agoin",
    category: "breakfast",
    price: 4500,
    img: "./images/item-7.jpeg",
    desc: `A high fibre diet of bread and beans can successfully tackle gout, an inflammatory arthritis, disease with sudden onset of acute pain `,
  },
  {
    id: 8,
    title: "Ofada Rice",
    category: "lunch",
    price: 1922,
    img: "./images/item-8.jpeg",
    desc: `Ofada rice is a popular Nigerian rice variety. It is also called Unpolished rice as it is rice in it's natural state and without genetic`,
  },
  {
    id: 9,
    title: "Garri and Groundnut",
    category: "shakes",
    price: 4200,
    img: "./images/item-9.jpeg",
    desc: `Soaked Garri as a 'cereal' where it is made with lukewarm water some milk and sugar plus or minus roasted groundnuts.`,
  },
  {
    id: 10,
    title: "Popcorn and Coke",
    category: "dinner",
    price: 7200,
    img: "./images/item-10.jpeg",
    desc: `Popcorn is a special type of corn that “pops” when exposed to heat. At the center of each kernel is a small amount of water`,
  },
];
